use joseestudillo;
!echo ------------------------------------------;
!echo table: joseestudillo.numeric_type_table;
!echo ------------------------------------------;
select * from joseestudillo.numeric_type_table;
!echo ------------------------------------------;
!echo table: joseestudillo.string_type_table ;
!echo ------------------------------------------;
select * from joseestudillo.string_type_table; 
!echo ------------------------------------------;
!echo table: joseestudillo.misc_type_table  ;
!echo ------------------------------------------;
select * from joseestudillo.misc_type_table;
!echo ------------------------------------------;
!echo table: joseestudillo.date_type_table;
!echo ------------------------------------------;
select * from joseestudillo.date_type_table; 
!echo ------------------------------------------;
!echo table: joseestudillo.array_type_table;
!echo ------------------------------------------;
select * from joseestudillo.array_type_table; 
!echo ------------------------------------------;
!echo table: joseestudillo.map_type_table;
!echo ------------------------------------------;
select * from joseestudillo.map_type_table; 
!echo ------------------------------------------;
!echo table: joseestudillo.struct_type_table;
!echo ------------------------------------------;
select * from joseestudillo.struct_type_table;
!echo ------------------------------------------;
!echo table: joseestudillo.union_type_table;
!echo ------------------------------------------;
select * from joseestudillo.union_type_table; 